from enum import Enum
from infrastructure.json_serializer import JsonSerializer
from os.path import expanduser

VERSION = 1
RESOURCE_GROUP_ID = 1
DEFAULT_RESOURCE_PATH = expanduser("~") + '/.PSI_P2P'

CATALOG_SERVICE_PORT = 30001
CATALOG_SERVICE_TIMEOUT = 5
CATALOG_SERVICE_BUFFER_LENGTH = 65535

CATALOG_PUBLISHER_AWAKE_PERIOD = 5
CATALOG_PUBLISHER_SEND_PERIOD = 30


TRANSFER_TRANSFER_PORT = 30002
LOCAL_RESOURCE_ADDRESS = '127.0.0.1'


class CATALOG_MESSAGES_TYPES(Enum):
    BROADCAST_ALL_FILES = 0
    ALL_FILES_REQUEST = 1


class RESPONSE_STATUSES(Enum):
    SUCCESS = 0
    BAD_REQUEST = 100
    REQUEST_DAMMAGED = 101
    VERSION_NOT_SUPPORTED = 102
    NOT_FOUND = 104
    SERVER_ERROR = 200


# register injection
InjectionContainer = {
    "serializer": JsonSerializer()
}
